'use client';

import React, { useState, useMemo } from 'react';
import { useProject } from '@/context/ProjectContext';
import {
    ClipboardList,
    Plus,
    Download,
    Upload,
    MoreHorizontal,
    ChevronRight,
    Trash2,
    Edit3,
    Search,
    Filter
} from 'lucide-react';
import { BoQItem, BoQCategory, BoQUnit, BoQCurrency } from '@/lib/types';
import { motion, AnimatePresence } from 'framer-motion';

// Utility to generate ID
const generateId = () => `boq_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;

export const BoQPage = () => {
    const { boqItems, setBoqItems, segments, equipmentList } = useProject();
    const [searchQuery, setSearchQuery] = useState('');
    const [categoryFilter, setCategoryFilter] = useState<BoQCategory | 'all'>('all');
    const [editingId, setEditingId] = useState<string | null>(null);

    // Calculate totals
    const totals = useMemo(() => {
        const total = boqItems.reduce((acc, item) => acc + item.total, 0);
        const byCategory: Record<BoQCategory, number> = {
            Mechanical: 0,
            Electrical: 0,
            Supports: 0,
            Consumables: 0,
            Services: 0
        };
        boqItems.forEach(item => { byCategory[item.category] += item.total; });
        return { total, byCategory };
    }, [boqItems]);

    // Filtered items
    const filteredItems = useMemo(() => {
        return boqItems.filter(item => {
            const matchesCategory = categoryFilter === 'all' || item.category === categoryFilter;
            const matchesSearch = item.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
                item.code.toLowerCase().includes(searchQuery.toLowerCase());
            return matchesCategory && matchesSearch;
        });
    }, [boqItems, categoryFilter, searchQuery]);

    // Actions
    const handleAddItem = () => {
        const newItem: BoQItem = {
            id: generateId(),
            category: 'Mechanical',
            code: '',
            description: 'New Item',
            quantity: 1,
            unit: 'pcs',
            unitPrice: 0,
            currency: 'EUR',
            total: 0,
            isAutoGenerated: false,
            isOverridden: false,
            updatedAt: new Date().toISOString()
        };
        setBoqItems([...boqItems, newItem]);
        setEditingId(newItem.id);
    };

    const handleUpdateItem = (id: string, updates: Partial<BoQItem>) => {
        setBoqItems(prev => prev.map(item => {
            if (item.id !== id) return item;
            const updated = { ...item, ...updates };
            updated.total = updated.quantity * updated.unitPrice;
            updated.updatedAt = new Date().toISOString();
            if (item.isAutoGenerated) updated.isOverridden = true;
            return updated;
        }));
    };

    const handleDeleteItem = (id: string) => {
        setBoqItems(prev => prev.filter(item => item.id !== id));
    };

    // Sync function from pipes/equipment (placeholder logic)
    const handleSyncFromDesign = () => {
        const pipeItems: BoQItem[] = segments.map(seg => ({
            id: generateId(),
            category: 'Mechanical' as BoQCategory,
            code: `PIPE-${seg.material.toUpperCase()}-${seg.size}`,
            description: `${seg.name || 'Pipe Segment'} - ${seg.size} (${seg.material})`,
            quantity: seg.length,
            unit: 'm' as BoQUnit,
            unitPrice: 0, // Price to be filled by user
            currency: 'EUR' as BoQCurrency,
            total: 0,
            isAutoGenerated: true,
            sourceId: seg.id,
            isOverridden: false,
            updatedAt: new Date().toISOString()
        }));

        const equipItems: BoQItem[] = equipmentList.map(eq => ({
            id: generateId(),
            category: 'Mechanical' as BoQCategory,
            code: `EQ-${(eq.manufacturer || 'GEN').toUpperCase().substring(0, 3)}-${eq.id.substring(0, 4)}`,
            description: `${eq.name} (${eq.type})`,
            quantity: 1,
            unit: 'pcs' as BoQUnit,
            unitPrice: eq.price || 0,
            currency: 'EUR' as BoQCurrency,
            total: eq.price || 0,
            isAutoGenerated: true,
            sourceId: eq.id,
            isOverridden: false,
            updatedAt: new Date().toISOString()
        }));

        // Filter out items that already have a matching sourceId
        const existingSourceIds = new Set(boqItems.filter(i => i.isAutoGenerated).map(i => i.sourceId));
        const newItems = [...pipeItems, ...equipItems].filter(item => !existingSourceIds.has(item.sourceId));

        if (newItems.length > 0) {
            setBoqItems([...boqItems, ...newItems]);
        }
    };

    // Category colors
    const categoryColors: Record<BoQCategory, string> = {
        Mechanical: 'bg-primary/10 text-primary border-primary/20',
        Electrical: 'bg-amber-500/10 text-amber-600 border-amber-500/20',
        Supports: 'bg-slate-500/10 text-slate-600 border-slate-500/20',
        Consumables: 'bg-rose-500/10 text-rose-600 border-rose-500/20',
        Services: 'bg-indigo-500/10 text-indigo-600 border-indigo-500/20'
    };

    return (
        <div className="flex flex-col flex-1 h-full min-h-0 bg-background/50 relative overflow-hidden">
            {/* Header */}
            <div className="flex-shrink-0 px-8 py-6 border-b border-border/40 bg-background/80 backdrop-blur-md z-10">
                <div className="flex flex-col gap-6">
                    {/* Breadcrumbs */}
                    <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground/60">
                        <span>Project</span>
                        <ChevronRight className="w-3 h-3" />
                        <span className="text-foreground">Bill of Quantities</span>
                    </div>

                    <div className="flex items-end justify-between">
                        <div>
                            <h1 className="text-3xl font-black text-foreground tracking-tight mb-2 flex items-center gap-3">
                                <ClipboardList className="w-8 h-8 text-primary" />
                                Bill of Quantities
                            </h1>
                            <p className="text-muted-foreground max-w-2xl text-sm font-medium">
                                Manage materials, equipment, and services for cost estimation and procurement.
                            </p>
                        </div>

                        <div className="flex items-center gap-3">
                            <button onClick={handleSyncFromDesign} className="btn btn-secondary gap-2 h-10">
                                <Download className="w-4 h-4" /> Sync from Design
                            </button>
                            <button className="btn btn-secondary gap-2 h-10">
                                <Upload className="w-4 h-4" /> Import Excel
                            </button>
                            <button onClick={handleAddItem} className="btn btn-primary gap-2 h-10">
                                <Plus className="w-4 h-4" /> Add Item
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* Toolbar */}
            <div className="px-8 py-4 border-b border-border/40 bg-muted/20 flex items-center gap-4">
                <div className="relative flex-1 max-w-md">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                    <input
                        type="text"
                        placeholder="Search by code or description..."
                        value={searchQuery}
                        onChange={e => setSearchQuery(e.target.value)}
                        className="w-full bg-background border border-border rounded-lg pl-10 pr-4 py-2 text-sm focus:ring-2 focus:ring-primary/20 focus:border-primary"
                    />
                </div>

                <div className="flex items-center gap-2">
                    <Filter className="w-4 h-4 text-muted-foreground" />
                    {(['all', 'Mechanical', 'Electrical', 'Supports', 'Consumables', 'Services'] as const).map(cat => (
                        <button
                            key={cat}
                            onClick={() => setCategoryFilter(cat)}
                            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all border ${categoryFilter === cat
                                    ? 'bg-primary text-primary-foreground border-primary'
                                    : 'bg-background border-border text-muted-foreground hover:border-primary/30'
                                }`}
                        >
                            {cat === 'all' ? 'All' : cat}
                        </button>
                    ))}
                </div>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-8 min-h-0">
                <div className="max-w-[1600px] mx-auto">
                    {/* Summary Cards */}
                    <div className="grid grid-cols-1 md:grid-cols-6 gap-4 mb-8">
                        <div className="md:col-span-2 bg-primary/5 rounded-2xl p-6 border border-primary/20">
                            <p className="text-xs font-bold text-primary uppercase tracking-wider mb-1">Total Estimate</p>
                            <p className="text-4xl font-black text-foreground">{totals.total.toLocaleString('en-EU', { minimumFractionDigits: 2 })} <span className="text-lg font-medium text-muted-foreground">EUR</span></p>
                            <p className="text-xs text-muted-foreground mt-2">{boqItems.length} items in list</p>
                        </div>
                        {Object.entries(totals.byCategory).map(([cat, value]) => (
                            <div key={cat} className={`bg-card rounded-xl p-4 border ${categoryColors[cat as BoQCategory].replace('text-', 'border-').split(' ')[2]}`}>
                                <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider mb-1">{cat}</p>
                                <p className="text-lg font-bold text-foreground">{value.toLocaleString('en-EU', { minimumFractionDigits: 0 })}</p>
                            </div>
                        ))}
                    </div>

                    {/* Table */}
                    <div className="bg-card rounded-2xl border border-border shadow-sm overflow-hidden">
                        <table className="w-full text-sm">
                            <thead className="bg-muted/50 border-b border-border">
                                <tr>
                                    <th className="text-left px-4 py-3 font-bold text-[10px] uppercase tracking-wider text-muted-foreground">Code</th>
                                    <th className="text-left px-4 py-3 font-bold text-[10px] uppercase tracking-wider text-muted-foreground">Description</th>
                                    <th className="text-left px-4 py-3 font-bold text-[10px] uppercase tracking-wider text-muted-foreground">Category</th>
                                    <th className="text-right px-4 py-3 font-bold text-[10px] uppercase tracking-wider text-muted-foreground">Qty</th>
                                    <th className="text-left px-4 py-3 font-bold text-[10px] uppercase tracking-wider text-muted-foreground">Unit</th>
                                    <th className="text-right px-4 py-3 font-bold text-[10px] uppercase tracking-wider text-muted-foreground">Unit Price</th>
                                    <th className="text-right px-4 py-3 font-bold text-[10px] uppercase tracking-wider text-muted-foreground">Total (EUR)</th>
                                    <th className="text-center px-4 py-3 font-bold text-[10px] uppercase tracking-wider text-muted-foreground">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-border/50">
                                <AnimatePresence>
                                    {filteredItems.map(item => (
                                        <motion.tr
                                            key={item.id}
                                            initial={{ opacity: 0, y: -10 }}
                                            animate={{ opacity: 1, y: 0 }}
                                            exit={{ opacity: 0, x: -20 }}
                                            className={`hover:bg-muted/30 transition-colors ${item.isAutoGenerated && !item.isOverridden ? 'bg-primary/5' : ''}`}
                                        >
                                            <td className="px-4 py-3 font-mono text-xs">{item.code}</td>
                                            <td className="px-4 py-3">
                                                {editingId === item.id ? (
                                                    <input
                                                        autoFocus
                                                        value={item.description}
                                                        onChange={e => handleUpdateItem(item.id, { description: e.target.value })}
                                                        onBlur={() => setEditingId(null)}
                                                        className="bg-background border border-border rounded px-2 py-1 w-full"
                                                    />
                                                ) : (
                                                    <span className="font-medium">{item.description}</span>
                                                )}
                                            </td>
                                            <td className="px-4 py-3">
                                                <span className={`text-[10px] font-bold px-2 py-1 rounded-full border ${categoryColors[item.category]}`}>
                                                    {item.category}
                                                </span>
                                            </td>
                                            <td className="px-4 py-3 text-right font-mono">{item.quantity.toFixed(2)}</td>
                                            <td className="px-4 py-3 text-muted-foreground">{item.unit}</td>
                                            <td className="px-4 py-3 text-right font-mono">{item.unitPrice.toFixed(2)}</td>
                                            <td className="px-4 py-3 text-right font-bold text-primary font-mono">{item.total.toFixed(2)}</td>
                                            <td className="px-4 py-3">
                                                <div className="flex items-center justify-center gap-1">
                                                    <button onClick={() => setEditingId(item.id)} className="p-1.5 rounded hover:bg-muted" title="Edit">
                                                        <Edit3 className="w-4 h-4 text-muted-foreground" />
                                                    </button>
                                                    <button onClick={() => handleDeleteItem(item.id)} className="p-1.5 rounded hover:bg-destructive/10" title="Delete">
                                                        <Trash2 className="w-4 h-4 text-destructive" />
                                                    </button>
                                                </div>
                                            </td>
                                        </motion.tr>
                                    ))}
                                </AnimatePresence>
                            </tbody>
                        </table>

                        {filteredItems.length === 0 && (
                            <div className="p-12 text-center text-muted-foreground">
                                <ClipboardList className="w-12 h-12 mx-auto mb-4 opacity-20" />
                                <p className="font-medium">No items yet</p>
                                <p className="text-xs mt-1">Click &quot;Add Item&quot; or &quot;Sync from Design&quot; to get started.</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};
