import { CatalogEquipment } from '@/lib/types';

/**
 * Catalog 3D — DOAR modele VERIFICATE pe Sketchfab (id-uri reale, confirmate în
 * research 2026). Modelele vechi cu id-uri inventate (ex. „5f8e6c4a4a7e4e8e…")
 * au fost eliminate; folosiți aceste intrări pentru galeria 3D.
 *
 * Pentru produsele noi fără model Sketchfab public (STULZ, Delta, CoolIT,
 * Rittal, nVent, Motivair) furnizorii publică fișiere BIM/CAD native
 * (PARTcommunity, stulz.com) — pot fi importate ca .glb.
 */
export const MODEL3D_CATALOG: CatalogEquipment[] = [
    // ============================================================
    // VERTIV — produse verificate (Sketchfab, 2024–2026)
    // ============================================================
    {
        id: 'vt-liebert-crv-3d',
        manufacturer: 'Vertiv',
        model: 'Liebert® CRV™ In-Row Cooling',
        category: 'CRAH / CCU',
        type: 'CRAH / CCU',
        description: 'Răcire in-row de înaltă densitate, 20–100 kW, compresor inverter, control iCOM.',
        volume: 8,
        weight: 320,
        power: 3,
        flowRate: 15,
        specifications: { coolingCapacity: '10-60kW' },
        model3d: 'https://sketchfab.com/models/58bcf436748a4b8db82e968323df0d56/embed',
    },
    {
        id: 'vt-liebert-exm-ups-3d',
        manufacturer: 'Vertiv',
        model: 'Liebert® EXM™ UPS (10–250 kVA)',
        category: 'Power',
        type: 'Altele',
        description: 'UPS trifazat online dublă conversie, 97% eficiență / 99% Eco Mode, opțiuni Li-ion. Model Sketchfab oficial Vertiv.',
        volume: 0,
        weight: 400,
        power: 200,
        specifications: { capacity: '10-250kVA', phase: '3-phase' },
        model3d: 'https://sketchfab.com/models/30aed814753d450d9fa6aaae83d29c19/embed',
    },
    {
        id: 'vt-onecore-3d',
        manufacturer: 'Vertiv',
        model: 'Vertiv™ OneCore — AI-Ready Data Center',
        category: 'Integrated Solutions',
        type: 'Altele',
        description: 'Centru de date prefabricat, pregătit IT/AI, anvelopă din oțel. Model Sketchfab oficial Vertiv (2025).',
        volume: 0,
        weight: 15000,
        power: 100,
        specifications: { series: 'OneCore' },
        model3d: 'https://sketchfab.com/models/f268dfa4a33846498843ee0e231b2418/embed',
    },

    // ============================================================
    // SCHNEIDER ELECTRIC / APC — produse verificate (2025 launch)
    // ============================================================
    {
        id: 'se-galaxy-vxl-3d',
        manufacturer: 'Schneider Electric',
        model: 'Galaxy VXL — UPS trifazat (500–1250 kW)',
        category: 'Power',
        type: 'Altele',
        description: 'Lansare 2025: 125 kW/3U module, 1.25 MW per frame, până la 1.042 kW/m², 99% eConversion, IEC 62443-4-2.',
        volume: 0,
        weight: 1200,
        power: 1250,
        specifications: { capacity: '500-1250kW', efficiency: '99% eConversion' },
        model3d: 'https://sketchfab.com/models/0e9df001eced4656837f4a266bf2ffda/embed',
    },
    {
        id: 'se-galaxy-vl-3d',
        manufacturer: 'Schneider Electric',
        model: 'Galaxy VL — UPS trifazat (200–500 kW)',
        category: 'Power',
        type: 'Altele',
        description: 'UPS trifazat 200–500 kW pentru datacenter, model Sketchfab oficial Schneider Electric.',
        volume: 0,
        weight: 900,
        power: 500,
        specifications: { capacity: '200-500kW' },
        model3d: 'https://sketchfab.com/models/28c88ce49d164223be1c3734b6a8e747/embed',
    },
    {
        id: 'se-galaxy-3l-pro-3d',
        manufacturer: 'Schneider Electric',
        model: 'Galaxy 3L Pro — UPS trifazat (400–600 kVA)',
        category: 'Power',
        type: 'Altele',
        description: 'Lansare 2025: 400–600 kVA @400V, baterii externe, conectat EcoStruxure. Model Sketchfab oficial (2025-03).',
        volume: 0,
        weight: 700,
        power: 600,
        specifications: { capacity: '400-600kVA' },
        model3d: 'https://sketchfab.com/models/cb50cbd789654092a82e175e5c91fd8f/embed',
    },
    {
        id: 'se-ecostruxure-pod-3d',
        manufacturer: 'Schneider Electric',
        model: 'EcoStruxure™ Pod Data Center',
        category: 'Integrated Solutions',
        type: 'Altele',
        description: 'Pod prefabricat modular, până la 1 MW+, cu răcire pe lichid, busway și containment. Model Sketchfab oficial SE.',
        volume: 0,
        weight: 3500,
        power: 500,
        specifications: { series: 'EcoStruxure Pod' },
        model3d: 'https://sketchfab.com/models/88f9d8c334d54be087343527c0f5eb03/embed',
    },
    {
        id: 'se-uniflair-inrow-rc-3d',
        manufacturer: 'Schneider Electric',
        model: 'Uniflair™ InRow RC (600mm)',
        category: 'In-Row Cooling',
        type: 'CRAH / CCU',
        description: 'Răcire in-row apropiată de rack, 70 kW, apă răcită. Model Sketchfab oficial Schneider Electric.',
        volume: 8,
        weight: 380,
        power: 4,
        flowRate: 12,
        specifications: { coolingCapacity: '70kW', width: '600mm' },
        model3d: 'https://sketchfab.com/models/e3422786fe34467d9893131e78e7e9e0/embed',
    },

    // ============================================================
    // PIPING — țevi, fittinguri, vane (modele verificate Sketchfab)
    // ============================================================
    {
        id: 'piping-pvc-fittings-socket-union',
        manufacturer: 'PVC-Fittings',
        model: 'Uniune filetată PVC (socket union, ø50 mm)',
        category: 'Piping',
        type: 'Altele',
        description: 'Racord rapid filetat pentru țevi PVC — util pentru detalii de conexiune.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/0b83235186d143e49158ddc714f90329/embed',
    },
    {
        id: 'piping-pvc-tee',
        manufacturer: 'PVC-Fittings',
        model: 'Teu filetat PVC',
        category: 'Piping',
        type: 'Altele',
        description: 'Ramurație Teu pentru rețele PVC, conexiuni filetate.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/c5569c1969a740ae8f571c4ff868395f/embed',
    },
    {
        id: 'piping-pvc-sanitary-kit',
        manufacturer: 'PolyPlex',
        model: 'Sistem țevi PVC sanitare (17 module + fittinguri, PBR 4K)',
        category: 'Piping',
        type: 'Altele',
        description: 'Kit modular complet: țevi + fittinguri, ideal pentru vizualizarea traseelor.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/e812f7c5bb57483cae591abb923ed938/embed',
    },
    {
        id: 'piping-imm-library-v1',
        manufacturer: 'IMM Pipes',
        model: 'Bibliotecă 30 țevi PPR — vol. 1 (cupoane, coturi, teuri, reducții, vane)',
        category: 'Piping',
        type: 'Altele',
        description: 'Set complet de fittinguri pentru o rețea de instalații — sugestiv pentru proiecte PPR/PE.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/c7189fad2f2c46e786545eb2b8a24734/embed',
    },
    {
        id: 'piping-imm-library-v2',
        manufacturer: 'IMM Pipes',
        model: 'Bibliotecă 30 țevi PPR — vol. 2',
        category: 'Piping',
        type: 'Altele',
        description: 'Volumul 2 al bibliotecii de țevi și racorduri.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/8776dfee482a4f51a3612698200ff98c/embed',
    },
    {
        id: 'piping-ppr-bend',
        manufacturer: 'PPR',
        model: 'Cot-bend țeavă PPR',
        category: 'Piping',
        type: 'Altele',
        description: 'Cot PPR pentru detalii de traseu.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/79c03fda56694e2dbba1a7eef291fbce/embed',
    },
    {
        id: 'piping-ppr-joint',
        manufacturer: 'PPR',
        model: 'Racord PPR 3/4"',
        category: 'Piping',
        type: 'Altele',
        description: 'Îmbinare PPR cu filet.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/9ed7c0b5cb3f427d835433f787df6ba6/embed',
    },
    {
        id: 'piping-gas-manifold',
        manufacturer: 'Instalații',
        model: 'Colector/ramificație conducte gaz',
        category: 'Piping',
        type: 'Altele',
        description: 'Manifold de distribuție pentru trasee de conducte.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/a40f7f2a9f2843b38ac9ee7b26365b13/embed',
    },
    {
        id: 'valve-ball-animated',
        manufacturer: 'SaVRee',
        model: 'Vană cu bilă (animație, training ingineresc)',
        category: 'Vane & Robineți',
        type: 'Altele',
        description: 'Vana cu bilă animată — explicativ pentru decupaje de proiect.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/f34f74a06f524177a51f1f9c4d3e1ccd/embed',
    },
    {
        id: 'valve-ball-pipeline',
        manufacturer: 'Kostroman',
        model: 'Vană cu bilă (pipeline)',
        category: 'Vane & Robineți',
        type: 'Altele',
        description: 'Robinet cu bilă pentru conducte de proces.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/4e3ad853ade140eba4f6f88830718ab3/embed',
    },
    {
        id: 'valve-ball-316ss',
        manufacturer: 'Lever',
        model: 'Vană cu bilă cu manetă (316 SS, NPT)',
        category: 'Vane & Robineți',
        type: 'Altele',
        description: 'Robinet oțel inox 316 cu pârghie.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/17fecf42f0ab486a8130b2c04c077f19/embed',
    },
    {
        id: 'valve-gate-wedge',
        manufacturer: 'Kozlov Maksim',
        model: 'Vană sertar cu pană (cuțit) — animată',
        category: 'Vane & Robineți',
        type: 'Altele',
        description: 'Vană cu sertar pentru izolare de traseu.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/dd989566c71b43a6a7ba44d2ab54146c/embed',
    },
    {
        id: 'valve-gate-spindle-basic',
        manufacturer: 'VIS-All-3D',
        model: 'Vană sertar cu tijă (basic)',
        category: 'Vane & Robineți',
        type: 'Altele',
        description: 'Vană cu tijă, versiune curată.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/02a88bb0f2b440e3a226a1bb2c74ac0d/embed',
    },
    {
        id: 'valve-check-flanged',
        manufacturer: 'shuping',
        model: 'Clapetă de reținere flanșată (cu marcaj)',
        category: 'Vane & Robineți',
        type: 'Altele',
        description: 'Clapetă pe flanșă pentru sens unic.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/f6642cb57d86413a9ce02d4588cbf564/embed',
    },
    {
        id: 'valve-crane-check-147xu',
        manufacturer: 'Crane Fluid Systems',
        model: 'Clapetă de sens Crane FS 147XU',
        category: 'Vane & Robineți',
        type: 'Altele',
        description: 'Clapetă de sens de la un producător real (Crane Fluid Systems) — importată din BIM.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/339c97669e5c4d669eef4ba6fbc561c6/embed',
    },
    {
        id: 'piping-utility-tunnel',
        manufacturer: 'Revit-BIM',
        model: 'Tunel utilitar — țevi & tăvi de cablu (Revit)',
        category: 'Piping',
        type: 'Altele',
        description: 'Model BIM de tunel tehnic cu conducte și cabluri.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/5140c7e8b536400c97a3f546dd58f1fd/embed',
    },

    // ============================================================
    // GENERATOARE DE CURENT & MOTOR-GENERATOARE
    // ============================================================
    {
        id: 'gen-caterpillar-style',
        manufacturer: 'Caterpillar (model artistic)',
        model: 'Generator Caterpillar',
        category: 'Generator',
        type: 'Altele',
        description: 'Generator industrial tip CAT pentru standby / back-up power.',
        volume: 0, weight: 8000, power: 500,
        model3d: 'https://sketchfab.com/models/60f789b1580a4848892e0131027d8751/embed',
    },
    {
        id: 'gen-diesel-4k',
        manufacturer: 'Generatoare',
        model: 'Generator diesel (4K PBR, descărcabil)',
        category: 'Generator',
        type: 'Altele',
        description: 'Genset diesel cu detalii PBR — prezentare back-up power.',
        volume: 0, weight: 6000, power: 400,
        model3d: 'https://sketchfab.com/models/7a0b72c7d01944a8aafab59d44eb120e/embed',
    },
    {
        id: 'gen-diesel-lowpoly',
        manufacturer: 'Generatoare',
        model: 'Generator diesel (low-poly PBR)',
        category: 'Generator',
        type: 'Altele',
        description: 'Grup electrogen diesel.',
        volume: 0, weight: 5000, power: 300,
        model3d: 'https://sketchfab.com/models/06eeb4c2df844edea8b982305ca8f050/embed',
    },
    {
        id: 'gen-mobile-trailer',
        manufacturer: 'Renafox',
        model: 'Generator diesel pe remorcă (mobil)',
        category: 'Generator',
        type: 'Altele',
        description: 'Genset mobil pe trailer — util pentru proiecte de șantier.',
        volume: 0, weight: 3000, power: 250,
        model3d: 'https://sketchfab.com/models/bff79fff851e4c6f98d48abe721ddd35/embed',
    },
    {
        id: 'gen-hydrogen',
        manufacturer: 'H2',
        model: 'Generator pe hidrogen (fuel-cell)',
        category: 'Generator',
        type: 'Altele',
        description: 'Agregat cu pile de combustie — trend pentru datacenter-uri verzi.',
        volume: 0, weight: 2000, power: 200,
        model3d: 'https://sketchfab.com/models/b6d6d719ff3248a684c12c3815238033/embed',
    },
    {
        id: 'gen-container-sci',
        manufacturer: 'MisterF1sh',
        model: 'Generator de putere containerizat',
        category: 'Generator',
        type: 'Altele',
        description: 'Grup electrogen în container — alimentare modulară.',
        volume: 0, weight: 9000, power: 1000,
        model3d: 'https://sketchfab.com/models/d3a4316fe9ac4967b51b2b1cb0bfa980/embed',
    },
    {
        id: 'gen-generac-vt1',
        manufacturer: 'Generac',
        model: 'Generac Towerlight VT1',
        category: 'Generator',
        type: 'Altele',
        description: 'Turn de iluminat + generator Generac (model oficial via BIM).',
        volume: 0, weight: 1200, power: 6,
        model3d: 'https://sketchfab.com/models/87c08e221dd74f6a82896871657bf1a6/embed',
    },
    {
        id: 'gen-generac-vt2',
        manufacturer: 'Generac',
        model: 'Generac Towerlight VT2 (6 kVA, super-silentios)',
        category: 'Generator',
        type: 'Altele',
        description: 'Generator silentios Generac pe remorcă.',
        volume: 0, weight: 1200, power: 6,
        model3d: 'https://sketchfab.com/models/4a384e75e994491bb5cfc412277fd16c/embed',
    },
    {
        id: 'engine-cummins-x12',
        manufacturer: 'Cummins',
        model: 'Motor Cummins X12',
        category: 'Generator',
        type: 'Altele',
        description: 'Motor diesel Cummins X12 — propulsie pentru agregate.',
        volume: 0, weight: 1000, power: 350,
        model3d: 'https://sketchfab.com/models/2810c2eec25a4bf4a7e27a472ee63782/embed',
    },
    {
        id: 'engine-cummins-x15',
        manufacturer: 'Cummins',
        model: 'Motor Cummins X15',
        category: 'Generator',
        type: 'Altele',
        description: 'Motor diesel Cummins X15 — platformă genset mare.',
        volume: 0, weight: 1100, power: 400,
        model3d: 'https://sketchfab.com/models/7ce75c3b7f9c4d759190fb027efccc53/embed',
    },

    // ============================================================
    // RACK-URI, SĂLI DE SERVER & CONTAINERE
    // ============================================================
    {
        id: 'rack-datacenter-lowpoly',
        manufacturer: 'DavidAnd3D',
        model: 'Rack datacenter (low-poly, PDU, cablare)',
        category: 'Racks',
        type: 'Altele',
        description: 'Rack cu PDU și management cabluri.',
        volume: 0, weight: 150,
        model3d: 'https://sketchfab.com/models/f178ec0a9c5f4605a5acbaaeb52dc721/embed',
    },
    {
        id: 'dc-room-lowpoly',
        manufacturer: 'Alex Martire',
        model: 'Sala de date (low-poly)',
        category: 'Racks',
        type: 'Altele',
        description: 'Sală mini-datacenter cu rafturi.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/59b31b45e80c484e98e1839ab1acc90b/embed',
    },
    {
        id: 'rack-server-detailed',
        manufacturer: 'EntropyNine',
        model: 'Rack servere detaliat',
        category: 'Racks',
        type: 'Altele',
        description: 'Rack de servere realistic.',
        volume: 0, weight: 200,
        model3d: 'https://sketchfab.com/models/01b49d9d1f694ba5b41e4b2b0e10d16e/embed',
    },
    {
        id: 'rack-ups-console',
        manufacturer: 'FlevasGR',
        model: 'Rack servere + UPS + consolă',
        category: 'Racks',
        type: 'Altele',
        description: 'Configurație rack cu UPS și console.',
        volume: 0, weight: 250,
        model3d: 'https://sketchfab.com/models/f24594ece9634cec9c1210c041838371/embed',
    },
    {
        id: 'rack-spellkaze',
        manufacturer: 'Spellkaze',
        model: 'Rack servere',
        category: 'Racks',
        type: 'Altele',
        description: 'Rack standard.',
        volume: 0, weight: 180,
        model3d: 'https://sketchfab.com/models/62f6779cb7e448b19aaf58544c3c7218/embed',
    },
    {
        id: 'rack-osho-detailed',
        manufacturer: 'Osho',
        model: 'Rack servere (25 texturi)',
        category: 'Racks',
        type: 'Altele',
        description: 'Rack detaliat cu 25 de texturi.',
        volume: 0, weight: 200,
        model3d: 'https://sketchfab.com/models/5320622f6c0741b7aed399bfa2965dc4/embed',
    },
    {
        id: 'rack-ridellco',
        manufacturer: 'Ridellco',
        model: 'Rack servere și consolă v3 (UPS + rack)',
        category: 'Racks',
        type: 'Altele',
        description: 'Configurație rack + UPS.',
        volume: 0, weight: 250,
        model3d: 'https://sketchfab.com/models/24ebe6f197c44e0a93f4010045c4a997/embed',
    },
    {
        id: 'server-room-highpoly',
        manufacturer: 'Scarecrow_original',
        model: 'Sală de servere (high-poly)',
        category: 'Racks',
        type: 'Altele',
        description: 'Sală de servere realistică.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/fe993fa15c254ee88677be6acec6b029/embed',
    },
    {
        id: 'dc-room-suite',
        manufacturer: 'luismi93',
        model: 'Sală servere v2 (access floor, NOC, UPS, pompă)',
        category: 'Racks',
        type: 'Altele',
        description: 'Suita completă de cameră tehnică — include planșeu ridicat, NOC și sală de putere.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/468911f09c3349cc98659067af5daf14/embed',
    },
    {
        id: 'container-shipping',
        manufacturer: 'SpatialNeglect',
        model: 'Containere de transport',
        category: 'Container',
        type: 'Altele',
        description: 'Container shipping standard — baza pentru module datacenter-ready.',
        volume: 0, weight: 2200,
        model3d: 'https://sketchfab.com/models/cc3f7136710f4905905eae1d10ac50b7/embed',
    },
    {
        id: 'container-classic',
        manufacturer: 'Sebastian Webster',
        model: 'Container classic (gameready)',
        category: 'Container',
        type: 'Altele',
        description: 'Container de transport — fundație pentru module containerizate.',
        volume: 0, weight: 2200,
        model3d: 'https://sketchfab.com/models/772f4be391a245f699c54e6cf157c58d/embed',
    },

    // ============================================================
    // COOLING & HVAC
    // ============================================================
    {
        id: 'hvac-chiller-rtac',
        manufacturer: 'Trane (stil RTAC)',
        model: 'Chiller răcit cu aer (HVAC v2.0, 4K)',
        category: 'Chiller',
        type: 'Altele',
        description: 'Chiller exterior răcit cu aer — importat pentru scheme de răcire.',
        volume: 60, weight: 3500, power: 150,
        model3d: 'https://sketchfab.com/models/dadc245779e84f9198d5fc1bfa8a7884/embed',
    },
    {
        id: 'hvac-chiller-cz',
        manufacturer: 'CZ351O',
        model: 'Chiller',
        category: 'Chiller',
        type: 'Altele',
        description: 'Agregat frigorific.',
        volume: 50, weight: 3000, power: 120,
        model3d: 'https://sketchfab.com/models/34787c7fc4c84f50a9048c0fa2039f18/embed',
    },
    {
        id: 'cooling-tower-photo',
        manufacturer: 'Metazeon',
        model: 'Turn de răcire (fotogrammetrie)',
        category: 'Cooling Tower',
        type: 'Altele',
        description: 'Turn de răcire fotogrammetric — referință pentru rețele de apă.',
        volume: 0, weight: 4000,
        model3d: 'https://sketchfab.com/models/ff3cdef5f8e24605b56648918e1f9a8a/embed',
    },
    {
        id: 'cooling-tower-atomic',
        manufacturer: 'MRowa',
        model: 'Turn de răcire termic',
        category: 'Cooling Tower',
        type: 'Altele',
        description: 'Turn de răcire pentru cicluri termice.',
        volume: 0, weight: 3000,
        model3d: 'https://sketchfab.com/models/7480a4f717854719b533b770efad7a23/embed',
    },
    {
        id: 'hvac-rooftop-animated',
        manufacturer: 'kubassa',
        model: 'Unitate HVAC pe acoperiș (animație)',
        category: 'AHU',
        type: 'Altele',
        description: 'Unități terasă pentru climă.',
        volume: 30, weight: 800, power: 20,
        model3d: 'https://sketchfab.com/models/0bf1acaa6f1d4a9bb38cfc91fd115f9c/embed',
    },
    {
        id: 'hvac-rooftop-set',
        manufacturer: 'M3D',
        model: 'Set sisteme HVAC (acoperiș)',
        category: 'AHU',
        type: 'Altele',
        description: 'Sisteme de răcire pe terasă.',
        volume: 40, weight: 1200, power: 30,
        model3d: 'https://sketchfab.com/models/f513e10b3914429f8a5b76972c2750a6/embed',
    },
    {
        id: 'hvac-pump-staffpick',
        manufacturer: 'OsamaDeep',
        model: 'Sistem de pompare HVAC',
        category: 'Grup Pompare',
        type: 'Grup Pompare',
        description: 'Pompă de circulație HVAC.',
        volume: 20, weight: 250, power: 5,
        model3d: 'https://sketchfab.com/models/eb957e4cb0bd489e926ee0075e58f0b0/embed',
    },
    {
        id: 'cray1-liquid-cooled',
        manufacturer: 'Cray',
        model: 'Cray-1 Supercomputer (răcit pe lichid)',
        category: 'Racks',
        type: 'Altele',
        description: 'Supercomputer legendar cu răcire pe lichid — istoric HPC.',
        volume: 0, weight: 5000,
        model3d: 'https://sketchfab.com/models/0ef677a2d6f04007a554b023126e6cb7/embed',
    },

    // ============================================================
    // ELECTRIC — switchgear, UPS, panouri, tăvi de cablu
    // ============================================================
    {
        id: 'el-sureset-mv',
        manufacturer: 'Schneider Electric',
        model: 'SureSeT — celulă MT cu aer izolat (15 kV, IEEE C37.20.2)',
        category: 'Switchgear',
        type: 'Altele',
        description: 'Celulă de medie tensiune Schneider Square D — model oficial BIM.',
        volume: 0, weight: 1200,
        model3d: 'https://sketchfab.com/models/f11d5bc882f54bedb55a8ce3a55b83e8/embed',
    },
    {
        id: 'el-switchgear-animated',
        manufacturer: 'skibigfx',
        model: 'Tablou de distribuție electrică (animație)',
        category: 'Switchgear',
        type: 'Altele',
        description: 'Celulă JT animată.',
        volume: 0, weight: 600,
        model3d: 'https://sketchfab.com/models/75cdfb1c20304ec4ae6b6def3673ad1c/embed',
    },
    {
        id: 'el-switchgear',
        manufacturer: 'skibigfx',
        model: 'Celulă electrică',
        category: 'Switchgear',
        type: 'Altele',
        description: 'Tablou electric.',
        volume: 0, weight: 600,
        model3d: 'https://sketchfab.com/models/46aae250934c4e7289fd387b2ea8c72c/embed',
    },
    {
        id: 'ups-vertiv',
        manufacturer: 'Vertiv',
        model: 'UPS Vertiv (model We3Do)',
        category: 'Power',
        type: 'Altele',
        description: 'Model UPS marca Vertiv — sugestiv pentru sălile de putere.',
        volume: 0, weight: 300, power: 100,
        model3d: 'https://sketchfab.com/models/c6e4388320e9414f830e5f3146138415/embed',
    },
    {
        id: 'ups-forza',
        manufacturer: 'We3Do',
        model: 'UPS Forza',
        category: 'Power',
        type: 'Altele',
        description: 'Sursă neîntreruptibilă compactă.',
        volume: 0, weight: 200, power: 50,
        model3d: 'https://sketchfab.com/models/686d6a393312497594e16fbe251c00af/embed',
    },
    {
        id: 'ups-cdp',
        manufacturer: 'We3Do',
        model: 'UPS CDP',
        category: 'Power',
        type: 'Altele',
        description: 'UPS pentru infrastructură critică.',
        volume: 0, weight: 250, power: 60,
        model3d: 'https://sketchfab.com/models/a79f0b1b868f4b0fa8b7959bdc5b0f20/embed',
    },
    {
        id: 'el-panel-8k',
        manufacturer: 'angryarcticfox',
        model: 'Panou electric de distribuție (8K)',
        category: 'Switchgear',
        type: 'Altele',
        description: 'Tablou de distribuție.',
        volume: 0, weight: 150,
        model3d: 'https://sketchfab.com/models/454393dd86874310a87dd6d4ee954b63/embed',
    },
    {
        id: 'el-panel-14mb',
        manufacturer: 'Mehdi Shahsavan',
        model: 'Panou electric',
        category: 'Switchgear',
        type: 'Altele',
        description: 'Panou electric.',
        volume: 0, weight: 150,
        model3d: 'https://sketchfab.com/models/394e96223cbf40e08c0f0c2afda95199/embed',
    },
    {
        id: 'el-panel-efimknife',
        manufacturer: 'efimknife',
        model: 'Panou electric',
        category: 'Switchgear',
        type: 'Altele',
        description: 'Panou electric.',
        volume: 0, weight: 150,
        model3d: 'https://sketchfab.com/models/54970d4284da4575a938d0bdfb6f021c/embed',
    },
    {
        id: 'cable-tray-modular',
        manufacturer: 'NotAnotherApocalypticCo.',
        model: 'Sistem tăvi de cablu (30 mesh-uri, modulare)',
        category: 'Infrastructure',
        type: 'Altele',
        description: 'Tăvi de cablu modulare cu grilă de 10 cm — planificare cablare.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/06b7ba70ae024fd88307e9c829d53d91/embed',
    },
    {
        id: 'cable-tray-models',
        manufacturer: 'm.usamahsafdar',
        model: 'Modele tăvi de cablu',
        category: 'Infrastructure',
        type: 'Altele',
        description: 'Tăvi de cablu — referință de traseu.',
        volume: 0, weight: 0,
        model3d: 'https://sketchfab.com/models/0b3518119f294b07aa2540ebb4c250aa/embed',
    },
];

